<?php
 $arrayText = array('รายการขนมขบเคี้ยว 1'     => 'file;snacklist1.json',
                    'รายการขนมขบเคี้ยว 2'     => 'file;snacklist2.json',
                    'รายการขนมขบเคี้ยว 3'     => 'file;snacklist3.json',
                    'ขนมขบเคี้ยว'             => 'json;/dbconn/itemslist.php?itmgrp=snack1',
                    'snack1'                => 'json;/dbconn/itemslist.php?itmgrp=snack1',
                    'snack2'                => 'json;/dbconn/itemslist.php?itmgrp=snack2',
                    'snack3'                => 'json;/dbconn/itemslist.php?itmgrp=snack3',
                    'snack4'                => 'json;/dbconn/itemslist.php?itmgrp=snack4',
                    'อาหาร'                 => 'json;/dbconn/itemslist.php?itmgrp=food1',
                    'เครื่องดื่ม'               => 'json;/dbconn/itemslist.php?itmgrp=drinking1',
                    'เบ็ดเตล็ด'               => 'json;/dbconn/itemslist.php?itmgrp=other1',
                    'Category'              => 'file;cate.json',
                    'ยกเลิกสั่งซื้อ'            => 'file;cancelorder.json',
                    'ยืนยันสั่งซื้อ'             => 'file;confirmorder.json',
                    'Profile'               => 'file;profilredit.json',
                    'CancelOrder'           => 'url;/dbconn/delorder.php',
                    'ConfirmOrder'          => 'url;/dbconn/conorder.php',
                    'ตะกร้า'                 => 'json;/dbconn/summary_order.php',
                    'chkord'                => 'json;/dbconn/confirm_order_list.php',
                    'pushord'               => 'json;/dbconn/confirm_order_list_push.php',
					'Hello'                 => 'สวีสดีจร้า');
?>