<?php
 $arrayText = array('รายการขนมขบเคี้ยว 1'     => 'file;snacklist1.json',
                    'รายการขนมขบเคี้ยว 2'     => 'file;snacklist2.json',
                    'รายการขนมขบเคี้ยว 3'     => 'file;snacklist3.json',
                    'ขนมขบเคี้ยว'             => 'json;/dbconn/itemslist.php?itmgrp=snack1',
                    'snack1'                => 'json;/dbconn/itemslist.php?itmgrp=snack1',
                    'snack2'                => 'json;/dbconn/itemslist.php?itmgrp=snack2',
                    'snack3'                => 'json;/dbconn/itemslist.php?itmgrp=snack3',
                    'snack4'                => 'json;/dbconn/itemslist.php?itmgrp=snack4',
                    'snack5'                => 'json;/dbconn/itemslist.php?itmgrp=snack5',
                    'snack6'                => 'json;/dbconn/itemslist.php?itmgrp=snack6',
                    'snack7'                => 'json;/dbconn/itemslist.php?itmgrp=snack7',
                    'snack8'                => 'json;/dbconn/itemslist.php?itmgrp=snack8',
                    'อาหาร'                 => 'json;/dbconn/itemslist.php?itmgrp=food1',
                    'food1'                 => 'json;/dbconn/itemslist.php?itmgrp=food1',
                    'food2'                 => 'json;/dbconn/itemslist.php?itmgrp=food2',
                    'food3'                 => 'json;/dbconn/itemslist.php?itmgrp=food3',
                    'food4'                 => 'json;/dbconn/itemslist.php?itmgrp=food4',
                    'food5'                 => 'json;/dbconn/itemslist.php?itmgrp=food5',
                    'food6'                 => 'json;/dbconn/itemslist.php?itmgrp=food6',
                    'food7'                 => 'json;/dbconn/itemslist.php?itmgrp=food7',
                    'food8'                 => 'json;/dbconn/itemslist.php?itmgrp=food8',
                    'เครื่องดื่ม'               => 'json;/dbconn/itemslist.php?itmgrp=drinking1',
                    'drinking1'             => 'json;/dbconn/itemslist.php?itmgrp=drinking1',
                    'drinking2'             => 'json;/dbconn/itemslist.php?itmgrp=drinking3',
                    'drinking3'             => 'json;/dbconn/itemslist.php?itmgrp=drinking4',
                    'drinking4'             => 'json;/dbconn/itemslist.php?itmgrp=drinking1',
                    'drinking5'             => 'json;/dbconn/itemslist.php?itmgrp=drinking5',
                    'drinking6'             => 'json;/dbconn/itemslist.php?itmgrp=drinking6',
                    'drinking7'             => 'json;/dbconn/itemslist.php?itmgrp=drinking7',
                    'drinking8'             => 'json;/dbconn/itemslist.php?itmgrp=drinking8',
                    'เบ็ดเตล็ด'               => 'json;/dbconn/itemslist.php?itmgrp=other1',
                    'other1'                => 'json;/dbconn/itemslist.php?itmgrp=other1',
                    'other2'                => 'json;/dbconn/itemslist.php?itmgrp=other2',
                    'other3'                => 'json;/dbconn/itemslist.php?itmgrp=other3',
                    'other4'                => 'json;/dbconn/itemslist.php?itmgrp=other4',
                    'other5'                => 'json;/dbconn/itemslist.php?itmgrp=other5',
                    'other6'                => 'json;/dbconn/itemslist.php?itmgrp=other6',
                    'other7'                => 'json;/dbconn/itemslist.php?itmgrp=other7',
                    'other8'                => 'json;/dbconn/itemslist.php?itmgrp=other8',
                    'Category'              => 'file;cate.json',
                    'ยกเลิกสั่งซื้อ'            => 'file;cancelorder.json',
                    'ยืนยันสั่งซื้อ'             => 'file;confirmorder.json',
                    'Profile'               => 'file;profilredit.json',
                    'CancelOrder'           => 'url;/dbconn/delorder.php',
                    'ConfirmOrder'          => 'url;/dbconn/conorder.php',
                    'ตะกร้า'                 => 'json;/dbconn/summary_order.php',
                    'chkord'                => 'json;/dbconn/confirm_order_list.php',
                    'pushord'               => 'json;/dbconn/confirm_order_list_push.php',
					'Hello'                 => 'สวีสดีจร้า');
?>